# Generated by Django 5.2 on 2025-05-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='itemmenu',
            options={'verbose_name': 'Item do Cardápio', 'verbose_name_plural': 'Itens do Cardápio'},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Alimentos', 'Alimentos'), ('Sobremesas', 'Sobremesas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PREPARACAO', 'Em Preparação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('metodo_entrega', models.CharField(blank=True, max_length=50)),
                ('endereco_entrega', models.TextField(blank=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
